on:
  push:
    branches:
      - main

jobs:
  terraform-and-docker:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (All infra)
        run: terraform apply -auto-approve

      - name: Show Terraform Outputs
        run: terraform output
      
      - name: Terraform Destroy
        run: terraform destroy -auto-approve 


      # ---------- Docker Build & Push ----------
      # Install AWS CLI on the self-hosted runner
      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
      #     sudo apt-get install -y awscli
      

      # - name: Log in to Amazon ECR
      #   shell: bash
      #   id: login-ecr
      #   run: |
      #     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      # - name: Build Docker Image
      #   run: |
      #     docker build -f docker/dockerfile -t my-app:latest .


      # - name: Tag Docker Image
      #   run: |
      #     docker tag my-app:latest ${{ secrets.ECR_URI }}:latest

      # - name: Push Docker Image to ECR
      #   run: |
      #     docker push ${{ secrets.ECR_URI }}:latest
